name: Deploy Mentor Bot

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd ${{ secrets.DEPLOY_PATH }}
            git fetch --all
            git reset --hard origin/main
            if [ -f venv/bin/pip ]; then
              venv/bin/pip install -r requirements.txt
            fi
            sudo systemctl restart mentor-bot

      - name: Log deployed version
        run: |
          VERSION=$(cat VERSION 2>/dev/null | tr -d ' \t\n\r')
          if [ -z "$VERSION" ]; then
            VERSION=unknown
          fi
          if git rev-parse --short HEAD >/dev/null 2>&1; then
            COMMIT=$(git rev-parse --short HEAD)
          else
            COMMIT=unknown
          fi
          echo "Mentor Bot v${VERSION} (commit ${COMMIT})"
